###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

languageCode: en
title: "La Trobe Design System"

## Preprocessor settings
markdown: kramdown
kramdown:
  input: GFM

## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
  sass_dir: assets/_sass

exclude:
    - build.sh
    - server.sh
    - gulpfile.js
    - build.config.js
    - package.json
    - package-lock.json
    - node_modules
    - vendor

## Outputs the navigation collections
collections:
  docs:
    output: true
    permalink: /:path
  ltu-components:
    output: true


## Sets the default attributes for the Documentation and Pattern Files
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "wedgetail"
  -
    scope:
      path: "_docs/guidelines"
    values:
      parentmenu: guideline
  -
    scope:
      path: "_docs/users"
    values:
      parentmenu: users
  -
    scope:
      path: "_docs/makers"
    values:
      parentmenu: makers
  -
    scope:
      path: "_docs/foundation"
    values:
      parentmenu: foundation
  -
    scope:
      path: "_docs/layout"
    values:
      parentmenu: 'layout'
  -
    scope:
      path: "_docs/navigation"
    values:
      parentmenu: navigation
  -
    scope:
      path: "_docs/content"
    values:
      parentmenu: 'content'
  -
    scope:
      path: "_docs/patterns"
    values:
      parentmenu: patterns
  -
    scope:
      path: "_docs/forms"
    values:
      parentmenu: form
  -
    scope:
      path: "_docs/examples"
    values:
      type: example
      parentmenu: example
  -
    scope:
      path: "_ltu-components/dist"
    values:
      layout: blank
  -
    scope:
      path: "_ltu-components/src"
    values:
      status: draft
      layout: snippet
      type: content
  -
    scope:
      path: "_ltu-components/test-pages"
    values:
      type: example
      layout: test-page-ds
