languageCode: en
title: "La Trobe Design System"
markdown: kramdown
kramdown:
  input: GFM
sass:
    sass_dir: ltu-patterns/assets/_sass
exclude:
    - build.sh
    - server.sh
defaults:
    -
        scope:
          path: "" # an empty string here means all files in the project
        values:
          layout: "default"
